"""Initial migration

Revision ID: 01463d5e0cf5
Revises: ecba5bbfc5a3
Create Date: 2026-07-24 21:52:11.956870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01463d5e0cf5'
down_revision: Union[str, None] = 'ecba5bbfc5a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
