"""Add pages and chunk_count to documents

Revision ID: cd287e63d47e
Revises: 01463d5e0cf5
Create Date: 2026-07-24 23:51:12.175521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd287e63d47e'
down_revision: Union[str, None] = '01463d5e0cf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('pages', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('chunk_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'chunk_count')
    op.drop_column('documents', 'pages')
    # ### end Alembic commands ###
