"""Phase 5 schema additions

Revision ID: ecba5bbfc5a3
Revises: f78e25edd7b9
Create Date: 2026-07-24 13:47:11.423323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecba5bbfc5a3'
down_revision: Union[str, None] = 'f78e25edd7b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('keywords', sa.Text(), nullable=True))
    op.add_column('query_logs', sa.Column('feedback', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('query_logs', 'feedback')
    op.drop_column('documents', 'keywords')
    op.drop_column('documents', 'summary')
    # ### end Alembic commands ###
