"""Initial schema

Revision ID: f78e25edd7b9
Revises: 
Create Date: 2026-07-24 13:06:59.882295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f78e25edd7b9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_query_logs_document_id', table_name='query_logs')
    op.drop_index('idx_query_logs_timestamp', table_name='query_logs')
    op.create_index(op.f('ix_query_logs_document_id'), 'query_logs', ['document_id'], unique=False)
    op.create_index(op.f('ix_query_logs_timestamp'), 'query_logs', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_query_logs_timestamp'), table_name='query_logs')
    op.drop_index(op.f('ix_query_logs_document_id'), table_name='query_logs')
    op.create_index('idx_query_logs_timestamp', 'query_logs', ['timestamp'], unique=False)
    op.create_index('idx_query_logs_document_id', 'query_logs', ['document_id'], unique=False)
    # ### end Alembic commands ###
